### ISSUE TITLE
Change REACT_APP_TILECACHE_URL to httpS

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/weather-anomaly-tool#50]
In file `.env`

**Comment by jameshiebert** [comment]
This may be a separate issue, but for some reason even if you pass the environment variable to the docker container, it doesn't get used... it still only uses what's in the `.env` file. We really want this to be configurable at runtime (that's why we're using an environment variable). Not sure what we have to do to make that happen...

**Comment by rod-glover** [comment]
It is a [separate issue](https://github.com/pacificclimate/weather-anomaly-tool/issues/51). Let's take the discussion there.

**Comment by rod-glover** [comment]
Superseded by use of pcic-react-leaflet-components
